log-debug-info: false
# If enabled, the plugin will modify messages after Spigot AsyncPlayerChatEvent listeners. Requires ProtocolLib.
modify-packets: false

enable-links: true
enable-ip-links: true
enable-commands: true
enable-copyable-text: true

format-links: '&n%s'
format-commands: '&n%s'
format-copyable-text: '&n%s'

# leave tooltip empty ('') to disable 
tooltip-links: ''
tooltip-commands: Copy command
tooltip-copyable-text: Copy text

# If disabled, the plugin will ignore whisper commands (/w, /msg, /tell)
do-whisper: true

# If disabled, the plugin will cancel the original message and send its own in vanilla format.
# If enabled, the original message will remain unchanged, and the plugin will send bare links in a new message.
whisper-separate-message: false

commands-remove-starting-dot: true
commands-run-on-click: false

copyable-text-begin-quotes: ',,'
copyable-text-end-quotes: ',,'