api-version: 1.14
name: ClickableLinks
version: 2.0.3
authors: [FEST_Channel, EvilGeniys]
description: Bring clickable links to minecraft chat!
website: https://github.com/festino-mc-plugins/ClickableLinks

main: com.festp.Main

commands:
         links:
           description: Configure plugin behaviour.
           #permission: clickablelinks.configure

permissions:
    clickablelinks.*:
        description: Gives access to all ClickableLinks commands
        children:
            clickablelinks.configure: true
    clickablelinks.configure:
        description: Allows the player to configure plugin behaviour.
        default: op
    clickablelinks.use.links:
        description: Allows the player to make links clickable.
        default: true
    clickablelinks.use.iplinks:
        description: Allows the player to make ip links clickable.
        default: true
    clickablelinks.use.commands:
        description: Allows the player to make commands clickable.
        default: true
    clickablelinks.use.copyable:
        description: Allows the player to make copyable text.
        default: true